//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class place_rating
    {
        public int Id { get; set; }
        public string place_id { get; set; }
        public Nullable<int> num_lv1 { get; set; }
        public Nullable<int> num_lv2 { get; set; }
        public Nullable<int> num_lv3 { get; set; }
        public Nullable<int> num_lv4 { get; set; }
    }
}
